apiVersion: v1
kind: Service
metadata:
  name: kamereon-poc
  labels:
    app: kamereon-poc
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP 
    nodePort: 31514
  selector:
    app: kamereon-poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamereon-poc
  labels:
    app: kamereon-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kamereon-poc
  template:
    metadata:
      labels:
        app: kamereon-poc
    spec:
      nodeSelector:
        nodeName: aks-agentpool-11820299-vmss000002
      containers:
      - name: kamereon-poc
        image: striver901/kamereon-poc
        ports:
          - containerPort: 8080