apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamereon-poc
  labels:
    app: kamereon-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kamereon-poc
  template:
    metadata:
      labels:
        app: kamereon-poc
    spec:
      containers:
      - name: kamereon-poc
        image: striver901/kamereon-poc
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"