kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: kmr-poc
  name: postgres-pv-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size